version: '3'

services:

### PHP-FPM Container #######################################
    php-fpm:
        build:
            context: ./php
        volumes:
            - ./code:/var/www/html
            - ./log/php:/var/log/php
        expose:
            - "9000"
        depends_on:
            - mysql
        networks:
            mynet:
                ipv4_address: 192.168.101.11

### Nginx Server Container ##################################
    nginx:
        build:
            context: ./nginx
        volumes:
            - ./code:/var/www/html
            - ./log/nginx:/var/log/nginx
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - php-fpm
        networks:
            mynet:
                ipv4_address: 192.168.101.11

### MySQL Container #########################################
    mysql:
        image: mysql:5.7
        volumes:
            - mysql-data:/var/lib/mysql
            - ./log/mysql:/var/log/mysql
        ports:
            - "3306:3306"
        networks:
            mynet:
                ipv4_address: 192.168.101.11
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=homestead
            - MYSQL_USER=homestead
            - MYSQL_PASSWORD=secret

### redis Container #########################################
    redis:
        image: redis
        volumes:
            - ./log/redis:/var/log/redis
        ports:
            - "6379:6379"
        networks:
            mynet:
                ipv4_address: 192.168.101.11

### Volumes Setup ###########################################
    volumes:
        mysql-data:

### networks Setup ###########################################    
    networks:
        mynet:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.0.0

    
