
version: '3'

services:

### PHP-FPM Container #######################################

    php-fpm:
      build:
        context: ./php
      volumes:
        - ./code:/var/www/html
        - ./log/php:/var/log/php-fpm
      expose:
        - "9000"
      depends_on:
        - mysql
      networks:
          - frontend
          - backend

### Nginx Server Container ##################################

    nginx:
      build:
        context: ./nginx
      volumes:
          - ./code:/var/www/html
          - ./log/nginx:/var/log/nginx
      ports:
          - "80:80"
          - "443:443"
      depends_on:
          - php-fpm
      networks:
          - frontend

### MySQL Container #########################################

    mysql:
      image: mysql:5.7
      volumes:
        - mysql-data:/var/lib/mysql
        - ./log/mysql:/var/log/msql
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=homestead
        - MYSQL_USER=homestead
        - MYSQL_PASSWORD=secret
      networks:
          - frontend

### Redis Container #########################################
    redis:
      image: redis
      volumes:
        - ./log/redis:/var/log/redis
      ports:
        - "6379:6379"
      networks:
          - backend

### Networks Setup ###########################################
networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"


### Volumes Setup ###########################################

volumes:
    mysql-data:
