
version: '3'

services:

### Nginx Server Container ##################################

    nginx:
      build:
        context: ./nginx
      volumes:          
          - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
          - ${NGINX_HTML_PATH}:/var/www/html
          - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      ports:
          - "${NGINX_HOST_HTTP_PORT}:80"
          - "${NGINX_HOST_HTTPS_PORT}:443"
      depends_on:
          - php-fpm

### PHP-FPM Container #######################################

    php-fpm:
      build:
        context: ./php
      volumes:
        - ./php:/var/www/html
        - ${PHP_FPM_LOG_PATH}:/var/log/php-fpm
      expose:
        - "9000"
      depends_on:
          - mysql

### MySQL Container #########################################

    mysql:
      image: mysql:5.7
      volumes:
        - mysql-data:/var/lib/mysql
        - ${MYSQL_LOG_PATH}:/var/log/msql
      ports:
        - "${MYSQL_PORT}:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}

### Redis Container #########################################

    redis:
      image: redis
      volumes:
        - ${REDIS_LOG_PATH}:/var/log/redis
      ports:
        - "${REDIS_PORT}:6379"

### Volumes Setup ###########################################

volumes:
    mysql-data:

