
version: '3'

services:

### Nginx Server Container ##################################

    nginx:
      image: gan068/nginx:latest
      volumes:          
          - ${NGINX_SITES_PATH}:/etc/nginx/sites-enabled
          - ${NGINX_HTML_PATH}:/var/www/html
          - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      ports:
          - "${NGINX_HOST_HTTP_PORT}:80"
          - "${NGINX_HOST_HTTPS_PORT}:443"
      depends_on:
          - php-fpm-71
          - php-fpm-56
          - php-fpm-55

### PHP-FPM Container #######################################

    php-fpm-71:
      image: gan068/php:php71
      volumes:
        - ${NGINX_HTML_PATH}:/var/www/html
        - ${PHP_FPM_LOG_PATH}:/var/log/php-fpm
      depends_on:
          - mariadb

    php-fpm-56:
      image: gan068/php:php56
      volumes:
        - ${NGINX_HTML_PATH}:/var/www/html
        - ${PHP_FPM_LOG_PATH}:/var/log/php-fpm
      depends_on:
          - mariadb

    php-fpm-55:
      image: gan068/php:php55
      volumes:
        - ${NGINX_HTML_PATH}:/var/www/html
        - ${PHP_FPM_LOG_PATH}:/var/log/php-fpm
      depends_on:
          - mariadb

### MySQL Container #########################################

    mariadb:
      image: mariadb:5.5.57
      ports:
        - "${MYSQL_PORT}:3306"
      volumes:
        - mysql-data:/var/lib/mysql
        - ${MYSQL_LOG_PATH}:/var/log/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      restart: always

### Redis Container #########################################

    redis:
      image: redis
      volumes:
        - ${REDIS_LOG_PATH}:/var/log/redis
      ports:
        - "${REDIS_PORT}:6379"

### Volumes Settings #########################################
volumes:
  mysql-data:
